print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input("6'2")
print("How much do you weight?", end=' ')
weight = input()
print(f"So, you´re {age} old, {height} tall and {weight} heavy.")
#height = float(height)
#weight = float(weight)
#IMC = weight / (height*height)
#print(f"Your IMC equals {IMC}")
